version: "3"
services:
  auth_service:
    build: auth_service
    ports:
      - target: 3999
        published: 3999

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/var/lib/mongo/data

